products:
  - name: Château de la Vallée
    description: Ce vin rouge riche et corsé offre des arômes de fruits noirs mûrs et d'épices, avec des tanins souples et une longue finale.
    quantity: 72
    vintage: 2018
    productFamily: Vin Rouge
    unitPrice: 25.99
    active:

  - name: Domaine des Vignobles
    description: Un vin blanc frais et vif aux notes d'agrumes et de fleurs blanches, avec une acidité équilibrée et une finale rafraîchissante.
    quantity: 36
    vintage: 2020
    productFamily: Vin blanc
    unitPrice: 19.99
    active:

  - name: Cuvée Royale
    description: Ce champagne élégant et pétillant séduit par ses arômes de fruits à chair blanche, de brioche et de miel, avec une effervescence fine et persistante.
    quantity: 48
    vintage: 2016
    productFamily: Vin Effervescent
    unitPrice: 45.99
    active:

  - name: Rosé de Provence
    description: Un rosé pâle et rafraîchissant aux notes de fraises et de fleurs, avec une texture soyeuse et une acidité vive.
    quantity: 0
    vintage: 2021
    productFamily: Vin Rosé
    unitPrice: 14.99

  - name: Barolo Classico
    description: Ce vin rouge italien prestigieux offre des arômes intenses de cerise, de truffe et de cuir, avec des tanins fermes et une longue persistance en bouche.
    quantity: 0
    vintage: 2016
    productFamily: Vin rouge
    unitPrice: 39.99
