productTransactionTypes:
  - name: Entrée à classifier
    description: Ajout au stock de produits sans classification.
    isEntry:

  - name: Sortie à classifier
    description: Sortie du stock de produits sans classification.

  - name: Stock existant
    description: Il s'agit de notre stock existant à la première utilisation de la suite d'outils informatique Negosud.
    isEntry:

  - name: Vente
    description: Il s'agit d'une vente.

  - name: Péremption
    description: Atteinte de la date de péremption du vin.

  - name: Casse par un employé
    description: Casse survenue lors de la manipulation des produits par un employé de Negosud.

  - name: Casse d'origine externe
    description: Casse quelconque.

  - name: Achat auprès d'un fournisseur
    description: Achat auprès d'un fournisseur de Negosud.
    isEntry:

  - name: Don de l'entrepôt Bichard
    description: Don du stock de l'entrepôt Bichard le 16 janvier 2024.
    isEntry:

  - name: Don à la mairie
    description: Don à la mairie de la commune, aussi appelé pot de vin.
